services:
  - type: web
    name: cloudpin-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist 
    buildFilter:
      paths:
        - Frontend/**
        - Frontend/**
        - render.yaml
    repoPath: Frontend
    routes:
      - type: rewrite
        source: /f/**
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: cloudpin-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    repoPath: Backend
    buildFilter:
      paths:
        - Backend/**
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGIN
        value: https://cloudpin-frontend.onrender.com
      - key: MONGODB_URI
        value: your-mongodb-connection-string

